#!/bin/python3

from tkinter import *  # imports everything related to the tkinter module, which is used for GUIs.

# widgets: GUI elements (budgets, text boxes, labels, images, etc)
# windows: a container to hold these widgets

window = Tk()  # creates an instance of a window

window.geometry("400x200")  # determines the size of the window

window.title("Hello!")  # gives the window a title

window.config(background="grey")  # adds a color background to the window. can also use the hex value of a color.

# icon = PhotoImage(file='filepath') adds an image in the top left corner of the window (instead of a feather)
# window.iconphoto(True,name_of_PhotoImage(ex: icon))

# ADDING AN IMAGE TO THE WINDOW.

photo = PhotoImage(file='HelloWorld.png')  # adds an image within the window.

# ADDING A BUTTON TO THE WINDOW.

def click():                               # The callback 'click' must be defined for us to use later.
    print("You clicked the button.")


button = Button(window,                    # adds a button within the window.
                text="Click here!",        # adds text to the button.
                command=click)             # callback.

button.pack()                              # displays the button within the window.)

# ADDING TEXT TO THE WINDOW.

label = Label(window,
              text="Hello, World!",  # label specifies the label to be added to the window.
              font=("Arial", 20),    # font is used to specify the font, font size, and style.
              fg="white",            # fg specifies the font color.
              bg="black",            # bg specifies the background for the font.
              relief=RIDGE,          # relief is used to add a border effect.
              bd=5,                  # bd changes the width of the border.
              image=photo,           # image adds an image to the widget.
              compound='bottom')     # compound allows more than one object to be added to the widget.

label.pack()  # displays the widget within the window.
# label.place() can be used to change the placement of the widget.

# ADDING AN ENTRY BOX TO THE WINDOW.

entry = Entry(window,                        # creates an entry box.
              font=("Times New Roman", 40))

entry.pack(side=RIGHT)                       # specifies where to place the entry box.


# ADDING A CHECK BUTTON/CHECKBOX TO THE WINDOW.

# The callback must be defined before we can use it.


def display():
    if(x.get())==1:                                                         # creating an if statement for if the button is checked.
        print("You agree to follow the rules for guest wifi use.")
    else:
        print("You have not agreed to follow the rules for guest wifi use.")


x = IntVar()

check_button = Checkbutton(window,
                           text="I have read the guest wifi user agreement.",
                           variable=x,                                      # setting a variable, x, for the check button.
                           onvalue=1,                                       # onvalue = button checked
                           offvalue=0,                                      # offvalue = button unchecked
                           command=display)

check_button.pack()                                                         # this is needed to display the check button in the window.


window.mainloop()  # displays window on the screen and listens for events
