#!/bin/python3

# KEYBOARD EVENTS

from tkinter import *

window = Tk()

def input(event):
    label.config(text=event.keysym)         # displays the keyboard events in the created window.
    # print("You pressed: " + event.keysym) is an alternative to the above. will display the keyboard 
        # events in the Run window.

window.bind("<Key>",input)                  # bind function needs an event and a function
                                            # our event is a keystroke. the function is input, which has been defined.

label = Label(window,font=("Consolas",40))  # this will allow text to be displayed in the window.
label.pack()

window.mainloop()
