#! /bin/python3


# READING AND WRITING TO NEW FILES, NAMED 'months' AND 'days', ARBITRARILY.
def nl():  # new line
    print('\n')\


# READING A FILE - file.close() should only be used once finished with the file, or python will throw an error.
months = open('months.txt')


print(months) # reads the file (gives us the file info)
print(months.mode) # tells us what mode we are in
print(months.readable()) # returns a boolean statement of if this is True or False


months.close()


nl()
print(months.read) # reads through all iterations


months.close()


nl()
print(months.readlines()) # reads line by line


months.close()


nl()
print(months.readlines()) # reads line by line
months.seek(0)
print(months.readlines()) # will read through the file from the beginning


months.close()


# Other methods of opening the file
months = open('months.txt')
for month in months:
    print(month)  # will read the file


for month in months:
    print(month.strip())  # removes the default space delimiter


months.close()


# WRITING TO A FILE - file.close() should only be used once finished with the file, or python will throw an error.
nl()
days = open('days.txt', "w")
days.write("Monday")  # writes to a new file


days.close()


nl()
days = open('days.txt', "w")  #overwrites the file contents
days.write("\nTuesday") 


days.close()


nl()
days = open('days.txt', "a")  #appends to the file


days.write("\nWednesday")  
days.close()



