#!/bin/python3

import matplotlib.pyplot as plt                 # importing the pyplot module as plt to save time instead of typing pyplot

input_values = [1, 2, 3, 4, 5, 6]
squares = [1, 4, 9, 16, 25, 36]                 # creating a list called squares

plt.style.use('seaborn')

# calling the subplots() function to generate one or more plots in a figure
fig, ax = plt.subplots()                        # fig represents the figure
ax.plot(input_values, squares, linewidth=3)     # ax represents a single plot in the figure

# Set chart title and label axes
ax.set_title("Square Numbers", fontsize=24)
ax.set_xlabel("Value", fontsize=14)
ax.set_ylabel("Square of Value", fontsize=14)

# Set size of tick labels
ax.tick_params(axis='both', labelsize=14)

plt.show()                                     # opens Matplotlib's viewer

