#! /bin/python3

import sys
import socket
from datetime import datetime

# Define the target
if len(sys.argv) == 2:
    target = socket.gethostbyname(sys.argv[1])  # translate hostname to ipv4
else:
    print("Invalid amount of argument.")
    print("Syntax: python3 scanner.py <ip>")
# Add a banner
print("-" * 50)
print("Scanning target "+target)
print("Time started: "+str(datetime.now()))
print("-" * 50)

try:
    for port in range(50,85):
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        socket.setdefaulttimeout(1)
        result = s.connect_ex((target,port))  # error indicator
        if result == 0:
            print(f"Port {port} is open")
        s.close()
        
except KeyboardInterrupt:  # we've stopped the program on our own (ctrl +c)
    print("\nExiting program.")
    sys.exit()
    
except socket.gaierror:  # the hostname does not resolve
    print("Hostname could not be resolved.")
    sys.exit()
    
except socket.error:
    print("Could not connect to server.")
    sys.exit()
