#!/bin/python3

import smtplib

sender = "sender@gmail.com"                                # sender email address.
receiver = "receiver@gmail.com"                            # recipent email address.
password = "password"                                      # email password.
subject = "Python Test Email"
body = "I wrote an email!"

message = f"""From: {sender}
To: {receiver}
Subject: {subject}\n
{body}
"""

server = smtplib.SMTP("smtp.gmail.com", 587)               # default port for gmail.
server.starttls()

try:
    server.login(sender, password)
    print("Logged in.")
    server.sendmail(sender, receiver, message)
    print("Email has been sent!")

except smtplib.SMTPAuthenticationError:                    # exception handling.
    print("Unable to sign in.")
