#!/bin/python3

import os.path
from tkinter import *
from tkinter import filedialog, colorchooser, font
from tkinter.messagebox import *
from tkinter.filedialog import *


def change_color():
    color = colorchooser.askcolor(title="Pick a color.")                            # opens the color chooser for the "Color" button.
    text_area.config(fg=color[1])                                                   # allows the color to be changed.


def change_font(*args):
    text_area.config(font=(font_name.get(), size_box.get()))                        # allows font name/size to be changed.


def new_file():                                                                     # clears current file and creates new file.
    window.title("Untitled")                                            
    text_area.delete(1.0, END)


def open_file():                                                                    # opens new file with default extension .txt
    file = askopenfilename(defaultextension=".txt",
                           file=[("All Files", "*.*"),
                                 ("Text Documents", "*.txt")])

    try:
        window.title(os.path.basename(file))
        text_area.delete(1.0, END)

        file = open(file, "r")

        text_area.insert(1.0, file.read())

    except Exception:                                                               # exception handling.
        print("Couldn't read file.")

    finally:
        file.close()


def save_file():                                                                    # saves file with default extension .txt
    file = filedialog.asksaveasfilename(initialfile="Untitled.txt",
                                        defaultextension=".txt",
                                        filetype=[("All Files", "*.*"),
                                                  ("Text Documents", "*.txt")])

    if file is None:
        return
    else:
        try:
            window.title(os.path.basename(file))
            file = open(file, "w")

            file.write(text_area.get(1.0, END))                                     # exception handling.

        except Exception:                                                               
            print("Couldn't save file.")
        finally:
            file.close()


# The cut, copy, and paste commands allow text to be cut, copied, and pasted. 
def cut():
    text_area.event_generate("<<Cut>>")


def copy():
    text_area.event_generate("<<Copy>>")


def paste():
    text_area.event_generate("<<Paste>>")


# Opens an 'About' message.
def about():
    showinfo("About This Program", "This is a Python program.")


# Quits the program by destroying the window.
def quit_program():
    window.destroy()


window = Tk()
window.title("Text Editor")
file = None

# Centering the window on the screen.
width = 500
height = 500
screen_width = window.winfo_screenwidth()
screen_height = window.winfo_screenheight()

x = int((screen_width / 2) - (width / 2))
y = int((screen_height / 2) - (height / 2))

window.geometry("{}x{}+{}+{}".format(width, height, x, y))

font_name = StringVar(window)
font_name.set("Calibri")

font_size = StringVar(window)
font_size.set("20")

text_area = Text(window, font=(font_name.get(), font_size.get()))

# Adding a scrollbar.
scroll_bar = Scrollbar(text_area)
scroll_bar.pack(side=RIGHT, fill=Y)
text_area.config(yscrollcommand=scroll_bar.set)

window.grid_rowconfigure(0, weight=1)
window.grid_columnconfigure(0, weight=1)
text_area.grid(sticky=N + E + S + W)

# Adds a frame to the window.
frame = Frame(window)
frame.grid()

# Adds a button to choose the font color.
color_button = Button(frame, text="Color", command=change_color)
color_button.grid(row=0, column=0)

# Adds an option menu to choose the font.
font_box = OptionMenu(frame, font_name, *font.families(), command=change_font)
font_box.grid(row=0, column=1)

# Adds a spinbox to set the font size.
size_box = Spinbox(frame, from_=1, to=100, textvariable=font_size, command=change_font)
size_box.grid(row=0, column=2)

# Adding the File, Edit, and About menus.
menu_bar = Menu(window)
window.config(menu=menu_bar)

file_menu = Menu(menu_bar, tearoff=0)
menu_bar.add_cascade(label="File", menu=file_menu)
file_menu.add_command(label="New", command=new_file)
file_menu.add_command(label="Open", command=open_file)
file_menu.add_command(label="Save", command=save_file)
file_menu.add_separator()
file_menu.add_command(label="Exit", command=quit)

edit_menu = Menu(menu_bar, tearoff=0)
menu_bar.add_cascade(label="Edit", menu=edit_menu)
edit_menu.add_command(label="Cut", command=cut)
edit_menu.add_command(label="Copy", command=copy)
edit_menu.add_command(label="Paste", command=paste)

about_menu = Menu(menu_bar, tearoff=0)
menu_bar.add_cascade(label="About", menu=about_menu)
about_menu.add_command(label="Help", command=about)

window.mainloop()
